apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-backend

resources:
  - namespace.yml
  - victoriametrics.yml
  - victorialogs.yml
  - tempo.yml
  - alloy-rbac.yml
  - alloy.yml
  - networkpolicy.yml
