# k8s/serviceaccount.yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-console
  labels:
    app.kubernetes.io/name: observability-console
    app.kubernetes.io/component: presentation-identity
