apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability-backend

resources:
  - ../../backend
  - tempo-minio-networkpolicy.yml

patches:
  - path: tempo-config-patch.yml
  - path: tempo-deployment-patch.yml
