apiVersion: v1
kind: ConfigMap
metadata:
  name: oco-shared-datasources
  labels:
    grafana_datasource: "1"
    app.kubernetes.io/part-of: homel-observability
data:
  shared-datasources.yml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        uid: victoriametrics
        type: prometheus
        access: proxy
        url: http://victoriametrics.observability-backend.svc.cluster.local:8428
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 15s
      - name: VictoriaLogs
        uid: victorialogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://victorialogs.observability-backend.svc.cluster.local:9428
        isDefault: false
        editable: false
        jsonData:
          derivedFields:
            - name: trace_id
              matcherType: label
              matcherRegex: trace_id
              url: '${__value.raw}'
              urlDisplayLabel: View trace
              datasourceUid: tempo
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.observability-backend.svc.cluster.local:3200
        isDefault: false
        editable: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: victorialogs
            spanStartTimeShift: "-5m"
            spanEndTimeShift: "5m"
            customQuery: true
            query: 'trace_id:="${__trace.traceId}"'
