# k8s/grafana/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: admin-secret
type: Opaque
stringData:
  admin-password: admin
